### ISSUE TITLE
301 error

### ISSUE THREAD

**Issue by dstig** [rmagrin/achecker#1]
Hi guys I'm getting a 301 error with this gem

api.rb:18:in `check': Error processing "https://www.google.com". Response status code 301 (RuntimeError)

**Comment by rmagrin** [comment]
Achecker changed their URL to require use of HTTPS and that broke the gem. I fixed it in version 0.0.9 and added the option to provide the url as a parameter, so it's possible work around it in case they change something in the future.

I can imagine that after 3 years it won't help you, but I wanted to leave it documented here.
